In [ ]:
#the coursera courses questions will come in the test

#making arrays using numpy module 

In [2]:
import numpy as np
a = np.array([1,2,3])
type(a)


numpy.ndarray

In [ ]:
'''0D array is a scalar and rest all is vector
in 0D array we only give value=>a = np.array(20)
in 1D array we give=> a = np.array([1,2,3])
in 2D array we give=> a = np.array([1,2,3](1D),[4,5,6](1D))
to only acces only ele 3 in 2D array=> a[0,2](this means 0th index of 2D array and 2nd index of 1st 1D array)'''

In [3]:
import numpy as np
a = np.array([1,2,3])#1D
b = np.array([[1,2,3],[4,5,6]])#2D, each ele is 1D array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])#3D, each ele is 2D array
print('a = ',a[2])#this all is in terms of index 
print('b = ',b[1,2])
print('c = ',c[1,0,1])


a =  3
b =  6
c =  8


In [4]:
print(c.ndim)#gives the dimension of c array which is 3 and for b it is 2

3


In [ ]:
'''slicing of array used to take a spefic dataset from a wide rage of datasets => nameofarray[start:end:step], start means inclusion, end means excluded and step means step value
eg: a = np.array[1,2,3,4,5,6,7]
print(a[2:5]) #this means that we only print from 2nd index to 5th index. If not given start index it takes 0 and if not given 
end index it takes till the last ele'''

In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[2:5])#prints from 2nd index to 5th index(excluding it)
print(a)#prints all the ele
print(a[:])#prints all the ele
print(a[-1:])#-ve means it starts from behind and -1 means 7
print(a[-2:])#as we say -2 so it starts from 7 and goes till 6 and prints 6 and 7 instead of 7 and 6 as it keeps the order same 
print(a[-7:-4])#here always the start index is smaller than the end index so we go till -7 which is 4 and prints till -4 which is 6
               #it will only print in the forward direction and not in backward direction.

[3 4 5]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[7]
[6 7]
[1 2 3]


In [ ]:
#going to start from the book